from . import (
    account_tax,
    artaza_magento_client,
    artaza_magento_rma,
    artaza_magento_source,
    artaza_magento_sync_log,
    artaza_magento_tax_class,
    magento_normalize,
    product_product,
    product_template,
    res_config_settings,
    sale_order,
    stock_picking,
    stock_quant,
    stock_warehouse,
)
