from . import magento_connector
from . import magento_cms_mixin
from . import cms_page
from . import cms_block
from . import product_template
from . import product_product
from . import stock_quant
from . import sale_order
from . import res_config_settings
